### ISSUE TITLE
HTML5 

### ISSUE THREAD

**Issue by roman-savitskyi** [ViGoIT/ViGo_Front_Project_v0.0.0#1]
This is Vitaliy Golubivskyy's Front Study Project.

GIT:
1) First commit with tag remove looks strange (+)
2) You don't use versions (+)
3) Work in one branch. Please prepare release for me (-)

Mark: 2/5

HTML:
1) You use standard HTML4 for input tags (-)
2) Problem with naming classes (-)
3) Additional tab symbols at the end of the rows and incorrect levels in doc. Aside in div as example. (-)
4) Use classname for all th in header of table. (+)

Mark: 6/10

**Comment by ViGoIT** [comment]
GIT:
1) It was just a part of my GIT Training, but was not a good idea to use same folder for main project;
3) Fixed: new branch name is work-on-issue; Added a new release.

HTML;
-moved new tags to new lines, exception is label-tag;
3) Fixed: removed all extra tabs;

**Comment by ViGoIT** [comment]
HTML:
- i don't agree about close tags, the code become unclear without them, so i am going to use them at least first time.

**Comment by ViGoIT** [comment]
HTML: 
- replaced img-tag by background for buttons(.btn-recycle, btn-plus)

**Comment by ViGoIT** [comment]
GIT: FIXED;
HTML: FIXED
1) I'm still about to use input-type="text", because don't see a sense to use both input-type=date and JS datapicker;
2) classes were renamed;
3) Fixed: removed all extra tabs;
4) Fixed: Used selector by tag.

**Comment by roman-savitskyi** [comment]
i don't agree about close tags, the code become unclear without them, so i am going to use them at least first time.

Standard HTML5 haven't close tag for single tag. 
So you must use it in task and in real projects. IT is today and our future

**Comment by ViGoIT** [comment]
Please take a look to Roman comment. That is why issue was reopened.

**Comment by ViGoIT** [comment]
Removed end tags for all input tags. Formatted HTML code. Issue has to be closed.
